In [1]:
import pandas as pd
import numpy as np

In [2]:
#Label Encoding - Ordinal Encoding 
#Label Encoder - for Y or ouput 
#Ordinal Encoder - for X or input features
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
0    30  Female  Average    School        No
20   57  Female  Average    School       Yes
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes

In [25]:
# all the categorical columns except the first two columns
df = df.iloc[:,2:]

In [26]:
df.head()

  purchased
0        No
1        No
2        No
3        No
4        No

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [29]:
X_train

   purchased
17       Yes
37       Yes
1         No
36       Yes
34        No
29       Yes
44        No
14       Yes
47       Yes
48       Yes
2         No
12        No
10       Yes
25        No
3         No
38        No
4         No
15        No
23        No
18        No
27        No
0         No
49        No
21        No
33       Yes
40        No
5        Yes
45       Yes
39        No
19       Yes
11       Yes
22       Yes
35       Yes
43        No
16       Yes
7        Yes
31       Yes
26        No
28        No
6         No

In [30]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [32]:
oe.fit(X_train)

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [24]:
# X_train = oe.transform(X_train)
# X_test_encoded = oe.transform(X_test)
X_train = oe.transform(X_train)

AttributeError: 'OrdinalEncoder' object has no attribute '_missing_indices'

In [33]:
X_train

   purchased
17       Yes
37       Yes
1         No
36       Yes
34        No
29       Yes
44        No
14       Yes
47       Yes
48       Yes
2         No
12        No
10       Yes
25        No
3         No
38        No
4         No
15        No
23        No
18        No
27        No
0         No
49        No
21        No
33       Yes
40        No
5        Yes
45       Yes
39        No
19       Yes
11       Yes
22       Yes
35       Yes
43        No
16       Yes
7        Yes
31       Yes
26        No
28        No
6         No