In [1]:
import numpy as np 
import pandas as pd

/var/folders/0d/2kwkrk3j5j373ss9sbf8sd6m0000gn/T/ipykernel_85842/118197663.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working With Dates

In [8]:
#Convertung to datetime datatype 
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1.Extract Year

In [10]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
786 2018-08-21         888       20       6       2018
615 2018-10-19        2846       22       3       2018
183 2019-02-08        4785       14       4       2019
959 2018-12-07        1700        8       2       2018
772 2018-11-05        6845       13       3       2018

2.Extract Month

In [11]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [13]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

Extract Days

In [14]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [16]:
#day of the week 
date['dat_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,dat_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [18]:
#day of week name 

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,dat_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [19]:
#is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday', 'Sunday']),1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,dat_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

Extract weel of the year

In [22]:
date['date_week'] = date['date'].dt.weekday

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,dat_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1
3,2019-08-17,2019,8,August,17,5,Saturday,1,5
4,2019-01-06,2019,1,January,6,6,Sunday,1,6

Extract Quarter

In [23]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,dat_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,5,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,1

Extract Semester

In [24]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)

date.drop(columns=['product_id','city_id', 'orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,dat_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,5,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,1,1

Extract Time elpased between dates

In [25]:
import datetime 

today = datetime.datetime.today()

today

datetime.datetime(2026, 8, 10, 19, 35, 31, 961631)

In [26]:
today - date['date']

0     2435 days 19:35:31.961631
1     2917 days 19:35:31.961631
2     2848 days 19:35:31.961631
3     2550 days 19:35:31.961631
4     2773 days 19:35:31.961631
                 ...
995   2863 days 19:35:31.961631
996   2804 days 19:35:31.961631
997   2652 days 19:35:31.961631
998   2717 days 19:35:31.961631
999   2491 days 19:35:31.961631
Name: date, Length: 1000, dtype: timedelta64[ns]

In [27]:
(today-date['date']).dt.days

0      2435
1      2917
2      2848
3      2550
4      2773
       ...
995    2863
996    2804
997    2652
998    2717
999    2491
Name: date, Length: 1000, dtype: int64

In [38]:
#Months passed 

np.round((today -date['date']) / np.timedelta64(1, 'm'),0)

0      3507576.0
1      4201656.0
2      4102296.0
3      3673176.0
4      3994296.0
         ...
995    4123896.0
996    4038936.0
997    3820056.0
998    3913656.0
999    3588216.0
Name: date, Length: 1000, dtype: float64

In [30]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [31]:
#Converting to datetime datatype 
time['date'] = pd.to_datetime(time['date'])

In [32]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [33]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

Extract Time Part

In [35]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Time difference

In [36]:
today - time['date']

0     4621 days 18:45:31.961631
1     4485 days 19:55:31.961631
2     4971 days 19:14:31.961631
3     4273 days 19:04:31.961631
4     4670 days 20:24:31.961631
                 ...
995   5260 days 18:45:31.961631
996   4581 days 20:21:31.961631
997   5046 days 19:58:31.961631
998   5162 days 20:01:31.961631
999   4434 days 20:10:31.961631
Name: date, Length: 1000, dtype: timedelta64[ns]

In [37]:
#in seconds 

(today - time['date']) /np.timedelta64(1, 's')

0      3.993219e+08
1      3.875757e+08
2      4.295637e+08
3      3.692559e+08
4      4.035615e+08
           ...
995    4.545315e+08
996    3.958717e+08
997    4.360463e+08
998    4.460689e+08
999    3.831702e+08
Name: date, Length: 1000, dtype: float64

In [39]:
#in minutes 

(today - time['date']) /np.timedelta64(1,'m')

0      6.655366e+06
1      6.459596e+06
2      7.159395e+06
3      6.154265e+06
4      6.726025e+06
           ...
995    7.575526e+06
996    6.597862e+06
997    7.267439e+06
998    7.434482e+06
999    6.386171e+06
Name: date, Length: 1000, dtype: float64

In [40]:
#in hours 

(today - time['date'])/np.timedelta64(1,'h')

0      110922.758878
1      107659.925545
2      119323.242212
3      102571.075545
4      112100.408878
           ...
995    126258.758878
996    109964.358878
997    121123.975545
998    123908.025545
999    106436.175545
Name: date, Length: 1000, dtype: float64