In [1]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv('dataset2.clean.csv')

In [4]:
df.head()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary(in rs),Career_Readiness_Level
0,1,NaN,Diploma,0.6,Cybersecurity Analyst,61,51-56,65,0,310,41.87,47.35,Unemployed,NaN,118274,Medium
1,2,NaN,NaN,8.4,?,59,NaN,NaN,2,175,50.91,79.52,?,NaN,32296,High
2,3,NaN,Bachelor,7.3-12.3,Data Analyst,48,57,92,7,35,30.15,47.31,Unemployed,UmV0YWls,26393,Low
3,4,25,Diploma,11.2,NaN,49,42-47,94,2,301,42.46,87.86-92.86,NaN,Finance,20121,High
4,5,38,NaN,0.4,NaN,NaN,66,66,?,291,90.29-95.29,NaN,Employed,Healthcare,25655,TG93

In [5]:
df['Age'].fillna(df['Age'].mean)

0        <bound method Series.mean of 0          NaN\n1...
1        <bound method Series.mean of 0          NaN\n1...
2        <bound method Series.mean of 0          NaN\n1...
3                                                       25
4                                                       38
                               ...
49995    <bound method Series.mean of 0          NaN\n1...
49996                                                   34
49997    <bound method Series.mean of 0          NaN\n1...
49998                                                41-46
49999                                                   26
Name: Age, Length: 50000, dtype: object

In [6]:
df.head()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary(in rs),Career_Readiness_Level
0,1,NaN,Diploma,0.6,Cybersecurity Analyst,61,51-56,65,0,310,41.87,47.35,Unemployed,NaN,118274,Medium
1,2,NaN,NaN,8.4,?,59,NaN,NaN,2,175,50.91,79.52,?,NaN,32296,High
2,3,NaN,Bachelor,7.3-12.3,Data Analyst,48,57,92,7,35,30.15,47.31,Unemployed,UmV0YWls,26393,Low
3,4,25,Diploma,11.2,NaN,49,42-47,94,2,301,42.46,87.86-92.86,NaN,Finance,20121,High
4,5,38,NaN,0.4,NaN,NaN,66,66,?,291,90.29-95.29,NaN,Employed,Healthcare,25655,TG93

In [ ]:
df.describe()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary(in rs),Career_Readiness_Level
count,50000,41885,41983,41964,42018,42142,41989,42183,41959,42015,42064,41843,42101,41953,42051,41976
unique,47891,85,15,599,15,121,121,121,17,1001,13045,13105,7,13,34480,7
top,1.00E+06,?,Diploma,?,Cybersecurity Analyst,?,?,?,2,?,?,?,Employed,Healthcare,?,Medium
freq,3,1935,5548,2061,4103,1944,2022,1943,4542,1982,2028,2068,9500,4794,2034,9277

In [8]:
df.info

<bound method DataFrame.info of           ID    Age   Education_Level Years_of_Experience  \
0          1    NaN           Diploma                 0.6
1          2    NaN               NaN                 8.4
2          3    NaN          Bachelor            7.3-12.3
3          4     25           Diploma                11.2
4          5     38               NaN                 0.4
...      ...    ...               ...                 ...
49995  49996    NaN  SGlnaCBTY2hvb2w=                 0.1
49996  49997     34                 ?                17.3
49997  49998    NaN            Master                 NaN
49998  49999  41-46      QmFjaGVsb3I=             3.0-8.0
49999  50000     26               NaN                 1.3

      Current_or_Target_Role Technical_Skill_Score Soft_Skill_Score  \
0      Cybersecurity Analyst                    61            51-56
1                          ?                    59              NaN
2               Data Analyst                    48               57
3                        NaN                    49            42-47
4                        NaN                   NaN               66
...                      ...                   ...              ...
49995      Software Engineer                    82               73
49996         Cloud Engineer                    72               55
49997           System Admin                    65               43
49998       TUwgRW5naW5lZXI=                    50               49
49999            ML Engineer                    73              NaN

      Domain_Knowledge_Score Certification_Count Training_Hours_Last_Year  \
0                         65                   0                      310
1                        NaN                   2                      175
2                         92                   7                       35
3                         94                   2                      301
4                         66                   ?                      291
...                      ...                 ...                      ...
49995                     78                   0                      160
49996                     74                   1                       90
49997                      ?              01-Jun                      389
49998                    NaN                   1                      NaN
49999                  91-96                   3                       87

      Skill_Gap_Score Readiness_Score Employment_Status          Industry  \
0               41.87           47.35        Unemployed               NaN
1               50.91           79.52                 ?               NaN
2               30.15           47.31        Unemployed          UmV0YWls
3               42.46     87.86-92.86               NaN           Finance
4         90.29-95.29             NaN          Employed        Healthcare
...               ...             ...               ...               ...
49995           41.89           12.07        Unemployed  SGVhbHRoY2FyZQ==
49996             NaN           71.08          Employed              SVQ=
49997           19.41           28.18          Employed          UmV0YWls
49998           77.13           54.07  VW5lbXBsb3llZA==     Manufacturing
49999           64.08            0.14      RW1wbG95ZWQ=               NaN

      Annual_Salary(in rs) Career_Readiness_Level
0                   118274                 Medium
1                    32296                   High
2                    26393                    Low
3                    20121                   High
4                    25655                   TG93
...                    ...                    ...
49995                80899                   High
49996                51223                   High
49997               139655                 Medium
49998                54558               TWVkaXVt
49999               127126                 Medium

[50000 rows x 16 columns]>

In [26]:
df = pd.get_dummies(df, columns=['Career_Readiness_Level'],dtype=int,drop_first=True)

KeyError: "None of [Index(['Career_Readiness_Level'], dtype='object')] are in the [columns]"

In [24]:
df.head()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,...,Readiness_Score,Employment_Status,Industry,Annual_Salary(in rs),Career_Readiness_Level_High,Career_Readiness_Level_Low,Career_Readiness_Level_Medium,Career_Readiness_Level_SGlnaA==,Career_Readiness_Level_TG93,Career_Readiness_Level_TWVkaXVt
0,1,?,Diploma,0.6,Cybersecurity Analyst,61,51-56,65,0,310,...,47.35,Unemployed,NaN,118274,0,0,1,0,0,0
1,2,?,NaN,8.4,?,59,NaN,NaN,2,175,...,79.52,?,NaN,32296,1,0,0,0,0,0
2,3,?,Bachelor,7.3-12.3,Data Analyst,48,57,92,7,35,...,47.31,Unemployed,UmV0YWls,26393,0,1,0,0,0,0
3,4,25,Diploma,11.2,NaN,49,42-47,94,2,301,...,87.86-92.86,NaN,Finance,20121,1,0,0,0,0,0
4,5,38,NaN,0.4,NaN,NaN,66,66,?,291,...,NaN,Employed,Healthcare,25655,0,0,0,0,1,0

In [20]:
df.head()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary(in rs),Career_Readiness_Level
0,1,?,Diploma,0.6,Cybersecurity Analyst,61,51-56,65,0,310,41.87,47.35,Unemployed,NaN,118274,Medium
1,2,?,NaN,8.4,?,59,NaN,NaN,2,175,50.91,79.52,?,NaN,32296,High
2,3,?,Bachelor,7.3-12.3,Data Analyst,48,57,92,7,35,30.15,47.31,Unemployed,UmV0YWls,26393,Low
3,4,25,Diploma,11.2,NaN,49,42-47,94,2,301,42.46,87.86-92.86,NaN,Finance,20121,High
4,5,38,NaN,0.4,NaN,NaN,66,66,?,291,90.29-95.29,NaN,Employed,Healthcare,25655,TG93